baseURL = 'https://panarchy.now/'
languageCode = 'ru-ru'
title = 'ПАНАРХИЯ СЕЙЧАС'
theme = 'hugo-book'

[params]
BookTheme = 'auto'
BookSection = '*'
BookRepo = 'https://github.com/panarchynow/panarchy.now'
BookComments = false
